<?php

use App\Models\Role;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BreedsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('lib_breeds')->delete();
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(1,1,'абиссинская');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(2,1,'американская жесткошерстная');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(3,1,'американская короткошерстная');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(4,1,'американский бобтейл');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(5,1,'американский кёрл');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(6,1,'ангорская');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(7,1,'балинезийская');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(8,1,'бенгальская');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(9,1,'бирманская ');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(10,1,'бомбейская');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(11,1,'британская голубая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(12,1,'британская короткошерстная');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(13,1,'бурма');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(14,1,'бурмилла');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(15,1,'гаванна');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(16,1,'герман рекс');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(17,1,'девон рекс');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(18,1,'домашняя');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(19,1,'донский сфинкс');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(20,1,'другая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(21,1,'европейская короткошерстная');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(22,1,'египетская мау');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(23,1,'канадский сфинкс');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(24,1,'кимрик');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(25,1,'корат');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(26,1,'корниш-рекс');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(27,1,'курильский бобтейл');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(28,1,'манкс');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(29,1,'манчкин');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(30,1,'мейн кун');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(31,1,'меконгский бобтейл');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(32,1,'мексиканская');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(33,1,'метис');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(34,1,'невская маскарадная');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(35,1,'норвежская лесная дымчато-голубая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(36,1,'ориентальная короткошерстная');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(37,1,'ориентальная длинношерстная');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(38,1,'охос азулес');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(39,1,'оцикет');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(40,1,'персидская');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(41,1,'пиксибоб');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(42,1,'русская голубая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(43,1,'рысь домашняя');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(44,1,'рэгдол');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(45,1,'селкирк-рекс');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(46,1,'сиамская');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(47,1,'сибирская');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(48,1,'сингапура');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(49,1,'скоттиш страйт');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(50,1,'скоттиш фолд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(51,1,'сноу-шу');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(52,1,'сомали');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(53,1,'сфинкс');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(54,1,'тайская');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(55,1,'тифани');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(56,1,'тонкинез');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(57,1,'турецкий ван');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(58,1,'цейлонская');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(59,1,'шартрез');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(60,1,'шиншилла');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(61,1,'шотландская вислоухая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(62,1,'экзотическая короткошерстная');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(63,1,'японский бобтейл');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(64,2,'австралийская борзая, кенгуровая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(65,2,'австралийская овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(66,2,'австралийский терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(67,2,'азавак');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(68,2,'аиди, атласская овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(69,2,'айну');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(70,2,'акбаш');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(71,2,'акита-ину');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(72,2,'алабай');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(73,2,'алапахский чистокровный бульдог');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(74,2,'альпийский спаниель');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(75,2,'альпине даксбракке');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(76,2,'аляскинский маламут');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(77,2,'американский бульдог');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(78,2,'американский водяной спаниель');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(79,2,'американский кокер спаниель');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(80,2,'американский питбультерьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(81,2,'американский стафордшир-терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(82,2,'американский той-фокстерьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(83,2,'американский фоксхаунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(84,2,'американский эскимоский шпиц');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(85,2,'анатолийский карабаш');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(86,2,'английская овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(87,2,'английский бульдог');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(88,2,'английский кокер спаниель');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(89,2,'английский мастиф');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(90,2,'английский пойнтер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(91,2,'английский сеттер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(92,2,'английский спрингер-спаниель');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(93,2,'английский той-терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(94,2,'английский фоксхаунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(95,2,'аппенцеллер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(96,2,'аргентинский дог');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(97,2,'арденский бувье');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(98,2,'армант, египетская овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(99,2,'артезиано-нормандский бассет');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(100,2,'артуазская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(101,2,'арьежская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(102,2,'афганская борзая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(103,2,'аффенпинчер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(104,2,'баварская горная гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(105,2,'балканская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(106,2,'банджарская борзая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(107,2,'барбе');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(108,2,'басенджи');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(109,2,'баскетмейкер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(110,2,'бассетхаунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(111,2,'беардед колли (хайланд колли)');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(112,2,'бедлингтон терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(113,2,'белый английский терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(114,2,'бельгийская лакенуа');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(115,2,'бельгийская малинуа');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(116,2,'бельгийский брак');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(117,2,'бельгийский гриффон');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(118,2,'бельгийский грюнендаль');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(119,2,'бельгийский ловенар');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(120,2,'бельгийский тервюрен');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(121,2,'бергамаско, бергамская овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(122,2,'бернер лауфхунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(123,2,'бернский зенненхунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(124,2,'бигль');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(125,2,'бийи');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(126,2,'бишон фризе');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(127,2,'бладхаунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(128,2,'блю лейси');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(129,2,'бобтейл, староанглийская овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(130,2,'бойкин спаниель');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(131,2,'боксёр');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(132,2,'Болонка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(133,2,'болонский бишон');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(134,2,'большая англо-французская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(135,2,'большая голубая гасконская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(136,2,'большая древесная гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(137,2,'большая пиринейская собака');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(138,2,'большая швейцарская горная пастушья собака');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(139,2,'большой вандейский гриффон');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(140,2,'большой мюнстерлендер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(141,2,'большой немецкий шпиц');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(142,2,'большой французский брак');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(143,2,'бордер колли');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(144,2,'бордер терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(145,2,'бордосский дог (французский мастифф)');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(146,2,'борзой, русская псовая борзая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(147,2,'бородатая колли');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(148,2,'босерон');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(149,2,'боснийская грубошерстная гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(150,2,'бостон-терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(151,2,'брабансон');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(152,2,'бракк дюпюи');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(153,2,'брандл-брак');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(154,2,'бретонский эпаньоль');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(155,2,'бриар');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(156,2,'бруно-де-юра');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(157,2,'брюссельский гриффон');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(158,2,'булленбайзер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(159,2,'бульмастиф');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(160,2,'бультерьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(161,2,'бультерьер миниатюрный');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(162,2,'бурбонский бракк');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(163,2,'бурбуль');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(164,2,'веймаренер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(165,2,'вельш корги кардиган');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(166,2,'вельш корги пемброук');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(167,2,'вельш-спрингер-спаниель');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(168,2,'вельштерьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(169,2,'венгерская борзая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(170,2,'вест хайленд уайт терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(171,2,'вестфальский таксообразный брак');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(172,2,'ветерхаунд, голландский спаниель');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(173,2,'водяной спаниель');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(174,2,'вольпино итальано');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(175,2,'восточно-европейская овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(176,2,'восточносибирская лайка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(177,2,'выжла, венгерская легавая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(178,2,'гавайская собака пои');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(179,2,'гаванский бишон');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(180,2,'гамильтонстёваре');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(181,2,'ганноверская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(182,2,'германский дратхаар');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(183,2,'германский жесткошерстный пойнтер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(184,2,'германский короткошерстный пойнтер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(185,2,'герта пойнтер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(186,2,'гладкошерстный ретривер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(187,2,'гладкошерстный фокстерьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(188,2,'глен-оф-имаал-терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(189,2,'голая собака инков');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(190,2,'голландская овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(191,2,'голландский смаусхонд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(192,2,'голландский тульпхонд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(193,2,'голубой гасконский бассет');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(194,2,'голубой овернский брак');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(195,2,'голубой пикардийский эпаньоль');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(196,2,'голубой хиллер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(197,2,'голштинская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(198,2,'гончая плотта');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(199,2,'гончая стефена');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(200,2,'гончая тальбота');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(201,2,'гордон-сеттер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(202,2,'гранди поденгу португезу');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(203,2,'грейхаунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(204,2,'гренландская собака');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(205,2,'греческая заячья гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(206,2,'греческая овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(207,2,'Гриффон');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(208,2,'гриффон кортальса');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(209,2,'далматин');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(210,2,'датский брохольмер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(211,2,'денди-динмонт терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(212,2,'джек-рассел-терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(213,2,'джиндо');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(214,2,'доберман-пинчер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(215,2,'дратхаар');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(216,2,'древер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(217,2,'древесная тенессийская тигровая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(218,2,'дрентская куропаточная собака');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(219,2,'другая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(220,2,'дункер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(221,2,'западно-сибирская лайка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(222,2,'зауерландский брак');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(223,2,'зауерландский хольцбрак');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(224,2,'золотистый ретривер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(225,2,'ирландский водяной спаниель');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(226,2,'ирландский волкодав (вольфхаунд)');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(227,2,'ирландский красно-белый сеттер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(228,2,'ирландский сеттер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(229,2,'ирландский терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(230,2,'исландская собака');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(231,2,'испанский брак, испанская легавая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(232,2,'испанский гальго, испанская борзая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(233,2,'испанский мастиф');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(234,2,'истрийская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(235,2,'итальянский брак');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(236,2,'йемтхунд, шведский элкхаунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(237,2,'йоркширский терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(238,2,'ка де бо');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(239,2,'Кавалер кинг чарльз спаниель');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(240,2,'кавказская овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(241,2,'кай кен');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(242,2,'кай лео');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(243,2,'кан да серра ди айреш');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(244,2,'кан да серра ди эштрела');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(245,2,'кан ди агуа');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(246,2,'кангал');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(247,2,'кане корсо');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(248,2,'каракачанская овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(249,2,'карело-финская лайка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(250,2,'карельская медвежья собака');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(251,2,'карликовый пинчер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(252,2,'каролинская собака');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(253,2,'карстская (красская) овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(254,2,'каталонская овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(255,2,'кеесхонд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(256,2,'келпи');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(257,2,'кентукская шел хип');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(258,2,'керн-терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(259,2,'керри блю терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(260,2,'керри-бигль');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(261,2,'кисю');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(262,2,'китайская хохлатая собака');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(263,2,'кламбер спаниель');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(264,2,'коикерхондье');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(265,2,'колли, шотландская овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(266,2,'комондор, венгерская овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(267,2,'котон де тулеар');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(268,2,'крапчато-голубой кунхаунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(269,2,'красный кунхаунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(270,2,'кромфорлендер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(271,2,'ксолойтцкуинтли');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(272,2,'кувас');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(273,2,'кунхаунд уолкера');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(274,2,'курляндская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(275,2,'курцхаар');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(276,2,'курчавый ретривер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(277,2,'куунхаунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(278,2,'лабрадор ретривер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(279,2,'лаготто-романьоло');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(280,2,'лангедокская пастушья собака');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(281,2,'лангхаар');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(282,2,'ландсир');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(283,2,'ланкаширский хилер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(284,2,'лапинкойра, финнский лаппхунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(285,2,'лапинпорокойра');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(286,2,'лапландский шпиц');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(287,2,'ларри');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(288,2,'левеск');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(289,2,'левретка, итальянская борзая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(290,2,'лёвхен, львиная собачка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(291,2,'лейкланд-терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(292,2,'леонбергер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(293,2,'леопардовая гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(294,2,'леопардовая собака катахулы');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(295,2,'лёрчер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(296,2,'литовская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(297,2,'лудогорская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(298,2,'лхасский апсо');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(299,2,'люненбургская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(300,2,'люцернер лауфхунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(301,2,'малая англо-французская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(302,2,'малый брабансон');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(303,2,'малый вандейский бассет-гриффон');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(304,2,'малый мюнстерлендер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(305,2,'малый французский брак');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(306,2,'мальтез, мальтийский бишон');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(307,2,'манчестерский терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(308,2,'маратхская борзая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(309,2,'маремма');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(310,2,'мастино наполетано');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(311,2,'медвежья канадская собака талтан');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(312,2,'медиу поденгу португезу');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(313,2,'метис');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(314,2,'микадо терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(315,2,'миниатюрный ксолойтцкуинтли');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(316,2,'мино');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(317,2,'миттельшнауцер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(318,2,'монтебёф');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(319,2,'мопс');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(320,2,'московская сторожевая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(321,2,'московский длинношерстный той-терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(322,2,'московский дракон');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(323,2,'московский короткошерстный той-терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(324,2,'муди');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(325,2,'немецкая овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(326,2,'немецкая оленегонная лайка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(327,2,'немецкий вахтельхунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(328,2,'немецкий вольфшпиц');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(329,2,'немецкий дог');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(330,2,'немецкий карликовый шпиц');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(331,2,'немецкий шпиц');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(332,2,'нивернейский гриффон');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(333,2,'новогвинейская поющая собака');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(334,2,'новошотландский ретривер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(335,2,'норботтен шпиц');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(336,2,'норвежский бухунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(337,2,'норвежский дункер хаунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(338,2,'норвежский лундехунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(339,2,'норвежский элкхаунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(340,2,'норвич-терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(341,2,'нормандская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(342,2,'норфолк терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(343,2,'ньюфаундленд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(344,2,'ойразир');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(345,2,'ойуки терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(346,2,'орхидея петербургская');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(347,2,'оттерхаунд, выдровая гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(348,2,'палевый бретонский бассет-гриффон');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(349,2,'папильон');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(350,2,'паттердейл-терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(351,2,'пекинес');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(352,2,'пекиньу поденгу португезу');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(353,2,'пердигейру португезу');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(354,2,'пердигеро де бургос');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(355,2,'пердигеро наварро');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(356,2,'перро де пастор мальоркин');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(357,2,'перро де преса мальоркин');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(358,2,'перро де пресса канарио');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(359,2,'перуанская орхидея инков');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(360,2,'пикардийская овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(361,2,'пинчер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(362,2,'пинчер миниатюрный');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(363,2,'пиринейская овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(364,2,'пиринейский мастиф');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(365,2,'подгальянская овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(366,2,'поденгу ди мастра');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(367,2,'поденгу ибисенко, ибисская собака');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(368,2,'польская низинная собака');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(369,2,'польский огар');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(370,2,'померанский шпиц');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(371,2,'понт-одмерский эпаньоль');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(372,2,'порселен, фарфоровая гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(373,2,'посавская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(374,2,'пражский крысарик');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(375,2,'пуатвен, пуатвинская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(376,2,'пудель');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(377,2,'пудель миниатюрный');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(378,2,'пудель стандартный');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(379,2,'пудель-пойнтер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(380,2,'пули');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(381,2,'пуми');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(382,2,'пшеничный мягкошерстный терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(383,2,'рампурская борзая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(384,2,'растреадор бразилейру');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(385,2,'рафейру ду алентежу');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(386,2,'ретривер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(387,2,'Риджбек');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(388,2,'ризеншнауцер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(389,2,'родезийский риджбек');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(390,2,'ротвейлер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(391,2,'румынская овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(392,2,'русская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(393,2,'русская пегая гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(394,2,'русский спаниель');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(395,2,'русский той-терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(396,2,'русский черный терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(397,2,'русско-европейская лайка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(398,2,'рэт-терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(399,2,'саарлосвольфхунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(400,2,'сабуесо эспаньоле де монте');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(401,2,'сабуэсо эспаньоль де монте');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(402,2,'салюки, персидская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(403,2,'самоедская лайка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(404,2,'санин');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(405,2,'сансю');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(406,2,'сегуджио итальяно');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(407,2,'сенбернар');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(408,2,'сен-жерменский брак');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(409,2,'серис');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(410,2,'сеттер-гордон');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(411,2,'сиба-ину');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(412,2,'сибирский хаски');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(413,2,'сийлихам терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(414,2,'сика ину');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(415,2,'сикоку');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(416,2,'силки терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(417,2,'синсю');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(418,2,'скай терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(419,2,'скотч терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(420,2,'словацкий копов');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(421,2,'словацкий чувач');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(422,2,'слюги, арабская борзая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(423,2,'смаусхонд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(424,2,'смитфильд-колли');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(425,2,'смоландстёваре, смоландская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(426,2,'солуки');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(427,2,'спиноне');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(428,2,'среднеазиатская овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(429,2,'средний шнауцер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(430,2,'средняя англо-французская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(431,2,'стабихаун');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(432,2,'стародатская легавая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(433,2,'стафордширский бультерьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(434,2,'стреллуфстёвер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(435,2,'суоменайокойра, финская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(436,2,'суоменпастикорва, финский шпиц');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(437,2,'суссекс-спаниель');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(438,2,'тазы (среднеазиатская борзая)');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(439,2,'тай риджбек');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(440,2,'тайган, киргизская борзая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(441,2,'такса гладкошерстная');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(442,2,'такса длинношерстная');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(443,2,'такса жесткошерстная');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(444,2,'такса кроличья');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(445,2,'такса миниатюрная');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(446,2,'такса стандартная');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(447,2,'теломиан');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(448,2,'тибетский мастиф');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(449,2,'тибетский спаниель');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(450,2,'тибетский терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(451,2,'тирольская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(452,2,'той-пудель');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(453,2,'той-терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(454,2,'тоса ину');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(455,2,'уест-хайланд-уайт-терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(456,2,'уипет');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(457,2,'фален, континентальный той-спаниель');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(458,2,'фараоновая собака');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(459,2,'фила бразилейру (бразильский мастиф)');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(460,2,'фильд спаниель');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(461,2,'финская лайка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(462,2,'финский шпиц');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(463,2,'фландрский бувье');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(464,2,'фокстерьер гладкошерстный');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(465,2,'фокстерьер жесткошерстный');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(466,2,'французская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(467,2,'французский бульдог');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(468,2,'французский эпаньоль');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(469,2,'фу куок');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(470,2,'халенденстёваре, хальденская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(471,2,'ханаанская собака');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(472,2,'харрьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(473,2,'хаски антарктическая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(474,2,'ховаварт');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(475,2,'хорватская овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(476,2,'хортая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(477,2,'хюгенхунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(478,2,'хюнерхунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(479,2,'цвергпинчер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(480,2,'цвергшнауцер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(481,2,'цвергшпиц');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(482,2,'чау-чау');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(483,2,'черный терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(484,2,'чесапик бей ретривер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(485,2,'чехословацкий влчак');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(486,2,'чешский терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(487,2,'чешский фоусек');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(488,2,'чинук');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(489,2,'чихуахуа');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(490,2,'шапендус');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(491,2,'шарпей');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(492,2,'шарпланинская овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(493,2,'швайсхунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(494,2,'шведский вальхунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(495,2,'швейцарская овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(496,2,'швейцарский лауфхунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(497,2,'шелти');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(498,2,'шиллерстёваре');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(499,2,'шипперке');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(500,2,'ши-тцу');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(501,2,'шотландский дирхаунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(502,2,'шотландский терьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(503,2,'штихельхаар');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(504,2,'энтлебухер зенненхунд');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(505,2,'эпаньоль нэн');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(506,2,'эрдели копо, трансильванская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(507,2,'эрдельтерьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(508,2,'эскимосская лайка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(509,2,'эстонская гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(510,2,'югославская грехцветная гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(511,2,'южная гончая');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(512,2,'южнорусская овчарка');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(513,2,'ягдтерьер');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(514,2,'японский хин');");
        DB::statement("insert into lib_breeds(id,kind_id,breed_name) values(515,2,'японский шпиц');");

        DB::statement("ALTER SEQUENCE lib_breeds_id_seq RESTART 516;");
    }
}
